import bootstrap
import streamlit as st

from app.config.theme import apply_theme, render_topbar, render_nav, render_page_header, section, page_footer

st.set_page_config(page_title="DBAS Tutorial", layout="wide", page_icon="??", initial_sidebar_state="collapsed")
apply_theme()
render_topbar()
render_nav("Dashboard")
render_page_header("DBAS Tutorial", "How to use the Driving Behaviour Analysis System end to end", badge="Guide")

section("Overview")
st.markdown("""
DBAS (Driving Behaviour Analysis System) classifies driving trips as **calm** or **aggressive** using DTW (Dynamic Time Warping) features and an SVM model. The system supports live scoring, fleet analytics, alerts, reports, and model insights.

At a high level:
1. Raw trips are converted to DTW features.
2. The SVM predicts calm vs aggressive.
3. Safety scores are calculated.
4. History and alerts are stored for analysis.
""")

section("Project Structure")
st.markdown("""
**app/**
- `main.py`: Landing dashboard with KPIs and fleet overview.
- `pages/`: Individual Streamlit pages.
- `components/`: Reusable UI elements (cards, charts).
- `config/theme.py`: Theme, layout, navigation, global styles.

**core/**
- `scoring/`: Prediction logic (`scorer.py`).
- `alerts/`: Alert engine.
- `profiling/`: Vehicle analytics.
- `reports/`: Report generation.
- `utils/`: Config loader and history manager.

**pipelines/**
- Scripts that build datasets and train models.

**data/processed/**
- `trips.csv`: Base trip data.
- `trips_features.csv`: DTW features + labels.
- `trip_history.csv`: Scored trip history.
- `alerts.csv`: Alert log.

**models/**
- `svm_model.pkl`: Trained SVM model.

**configs/config.yaml**
- Central path + threshold configuration used across the app.
""")

section("Pipeline Workflow")
st.markdown("""
To keep the model and features up to date, run the pipeline in this order:

1. `pipelines/step1_generate.py`  
   Generates or collects raw trip data.

2. `pipelines/step2_eda.py`  
   Performs exploratory analysis and sanity checks.

3. `pipelines/step3_dtw_features.py`  
   Computes DTW distances to calm and aggressive templates and writes `data/processed/trips_features.csv`.

4. `pipelines/step4_svm_train.py`  
   Trains the SVM model and saves it to `models/svm_model.pkl`.

5. `pipelines/step5_evaluate.py`  
   Evaluates model performance and diagnostic outputs.
""")

section("Live Scoring")
st.markdown("""
The **Live Scoring** page lets you score a new trip interactively.

Typical flow:
1. Provide trip inputs or upload a file.
2. DTW features are computed.
3. The SVM model predicts the label.
4. A safety score is computed.
5. Results are logged in `trip_history.csv`.
6. If below alert threshold, an alert is logged in `alerts.csv`.
""")

section("Alerts")
st.markdown("""
The **Alerts** page surfaces trips that fell below the alert threshold (default 40). It highlights critical and warning trips and makes it easier to prioritize investigation.

Alert behavior is controlled in `configs/config.yaml` and implemented in `core/alerts/alert_engine.py`.
""")

section("Vehicle Profile")
st.markdown("""
The **Vehicle Profile** page provides a per-vehicle deep dive:
- Total trips
- Average safety score
- Aggressive trip percentage
- Score trend over time
- Risk summary
- Full trip log
""")

section("Driver Leaderboard")
st.markdown("""
The **Driver Leaderboard** ranks vehicles by safety score and aggressive-trip ratio, giving a fleet-wide performance snapshot.
""")

section("Reports")
st.markdown("""
The **Reports** page generates shareable summaries for stakeholders. Reports are generated by `core/reports/report_generator.py` and saved under `outputs/reports/`.
""")

section("Model Performance")
st.markdown("""
The **Model Performance** page explains the model internals and performance:
- KPI metrics (accuracy, F1, precision, recall)
- Confusion matrix
- Feature importance (Random Forest)
- Model comparison table
- DTW feature scatter plot
- Safety score distribution
- DTW template comparison
- Cross-validation results
""")

section("Configuration")
st.markdown("""
All paths and thresholds live in `configs/config.yaml`. These values are loaded by `core/utils/config.py` and used across the app and pipelines.

Key fields:
- `model_path`
- `features_path`
- `history_path`
- `alerts_path`
- `risk_thresholds`
""")

section("Troubleshooting")
st.markdown("""
**No feature data found**  
Run `pipelines/step3_dtw_features.py` and `pipelines/step4_svm_train.py`.

**No trip history available**  
Run a live score to populate `trip_history.csv`.

**Alerts not triggering**  
Check safety thresholds in `configs/config.yaml` and confirm scoring logic.
""")

page_footer()
